### ISSUE TITLE
Please clean up your requirements.

### ISSUE THREAD

**Issue by amcgregor** [kevinadhiguna/instagram-profpic-downloader#1]
Exactly the same problem as per: kevinadhiguna/link-shortener#1

Be sure you prune your `pip freeze` generated requirements before committing them.

Thank you.

**Comment by kevinadhiguna** [comment]
Hello @amcgregor ! Thanks for reporting the issue, I think [the latest commit](https://github.com/kevinadhiguna/instagram-profpic-downloader/commit/68bfbbf56fdfd30a219393ce5017d20363f5759d) should fix this. Feel free to tell if the issue still exists, thank you!

**Comment by amcgregor** [comment]
Thank you very much, and apologies for the cross-project e-mail notification spam I must have triggered; thought you may wish to individually track corrections.

Thank you again! (Time for another spam-wave. 😭) ×4
